apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "krakend-manager.fullname" . }}
  labels:
    {{- include "krakend-manager.labels" . | nindent 4 }}
  {{- if .Values.reloader.enabled }}
  annotations:
    configmap.reloader.stakater.com/reload: "cm-{{ include "krakend-manager.fullname" . }}"
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      version: {{ .Chart.AppVersion }}
      {{- include "krakend-manager.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        {{- include "krakend-manager.annotations" . | nindent 8 }}
      labels:
        version: {{ .Chart.AppVersion }}
        {{- include "krakend-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MICRO_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKey.name }}
                  key: {{ .Values.secretKey.database.user }}
            - name: MICRO_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKey.name }}
                  key: {{ .Values.secretKey.database.pass }}
            - name: MICRO_REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKey.name }}
                  key: {{ .Values.secretKey.redis }}
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: LOG_STDOUT
              value: {{ .Values.log.std | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.log.level }}
          ports:
            - name: http
              containerPort: {{ .Values.service.http }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.service.grpc }}
              protocol: TCP
            {{- if .Values.metric.enabled }}
            - name: metric
              containerPort: {{ .Values.metric.port }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            {{- if .Values.filebeat.enabled }}
            - name: log-volume
              mountPath: /var/log/microwe
            {{- end}}
            - name: cm-{{ include "krakend-manager.name" . }}
              mountPath: /etc/microwe
          {{- if .Values.probe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.liveness }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.readiness }}
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.filebeat.enabled }}
        - name: filebeat
          image: "{{ .Values.filebeat.registry }}/{{ .Values.filebeat.repository }}:{{ .Values.filebeat.tag }}"
          imagePullPolicy: {{ .Values.filebeat.pullPolicy }}
          volumeMounts:
          - name: log-volume
            mountPath: /var/log/microwe
          - name: filebeat-log
            mountPath: /usr/share/filebeat/filebeat.yml
            subPath: filebeat.yml
        {{- end }}
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/{{ .Values.timezone }}
        - name: cm-{{ include "krakend-manager.name" . }}
          configMap:
            name: cm-{{ include "krakend-manager.fullname" . }}
        {{- if .Values.filebeat.enabled }}
        - name: log-volume
          emptyDir: {}
        - name: filebeat-log
          configMap:
            name: filebeat-log
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
