apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "krakend-monitor.fullname" . }}
  labels:
    {{- include "krakend-monitor.labels" . | nindent 4 }}
  {{- if .Values.reloader.enabled }}
  annotations:
    configmap.reloader.stakater.com/reload: "cm-{{ include "krakend-monitor.fullname" . }}"
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      version: {{ .Chart.AppVersion }}
      {{- include "krakend-monitor.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        {{- include "krakend-monitor.annotations" . | nindent 8 }}
      labels:
        version: {{ .Chart.AppVersion }}
        {{- include "krakend-monitor.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: sa-{{ include "krakend-monitor.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKey.name }}
                  key: {{ .Values.secretKey.database.user }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKey.name }}
                  key: {{ .Values.secretKey.database.pass }}
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: LOG_STDOUT
              value: {{ .Values.log.std | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.log.level }}
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: cm-{{ include "krakend-monitor.name" . }}
              mountPath: /etc/microwe
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/{{ .Values.timezone }}
        - name: cm-{{ include "krakend-monitor.name" . }}
          configMap:
            name: cm-{{ include "krakend-monitor.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
