---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ include "krakend-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-{{ include "krakend-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - get
      - watch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-{{ include "krakend-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-{{ include "krakend-monitor.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: sa-{{ include "krakend-monitor.fullname" . }}
    namespace: {{ .Release.Namespace }}