apiVersion: v1
kind: Service
metadata:
  name: {{ include "micro-base.fullname" . }}
  labels:
    {{- include "micro-base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "micro-base.selectorLabels" . | nindent 4 }}
