---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ include "micro-auth.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-{{ include "micro-auth.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-{{ include "micro-auth.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-{{ include "micro-auth.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: sa-{{ include "micro-auth.fullname" . }}
    namespace: {{ .Release.Namespace }}