apiVersion: v1
kind: Service
metadata:
  name: {{ include "wegpt.fullname" . }}
  labels:
    {{- include "wegpt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodeHttp }}
      {{- end }}
  selector:
    {{- include "wegpt.selectorLabels" . | nindent 4 }}
